# .github/workflows/build.yml
name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build with Make
      run: |
        cd build
        make -j$(nproc)
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build test
        run: | 
          mkdir -p build 
          cd build
          cmake .. -DSLANG_DEBUG=ON
          make
      - name: Run test
        run: |
          make
          ./slang examples/basics.slang
          ./slang examples/functions.slang
          ./slang examples/logic.slang
          ./slang examples/synths.slang
  image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t slang:latest .

      - name: Tag image
        run: |
          docker tag slang:latest ${{ secrets.DOCKER_USERNAME }}/slang:latest

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/slang:latest
